services:
  clickhouse-db:
    image: clickhouse:latest
    container_name: clickhouse
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=""
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server
  postgres-db:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_DB=default
      - POSTGRES_PASSWORD=default
      - POSTGRES_USER=default
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  clickhouse_data:
  clickhouse_log:
  postgres_data:
    